### ISSUE TITLE
注意了子项目【移动小商城：基于node，包含前后台】中植入脚本病毒

### ISSUE THREAD

**Issue by Jireh012** [ritaswc/wechat_app_template#1]
repos\wechat_app_template-master\2017-02-24\移动小商城：基于node，包含前后台\后台\public\src\modules\user\tpl\login.html

这只是其中一个Html文件，在后台其他子模块的html文件当中都有这段脚本病毒

![image](https://user-images.githubusercontent.com/19604856/76837081-e373df80-686c-11ea-82c6-cdf755a50547.png)

**Comment by Jireh012** [comment]
还有芒果TV中也有

**Comment by ritaswc** [comment]
好的，我修改一下再传上去，这个是我搜集来的
